config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios

  get 'angular-items', to: 'portfolios#angular'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :blogs do 
    member do
      get :toggle_status
    end
  end


  root to:'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

	has_many :technologies

	accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }


	validates_presence_of :title, :body, :main_image, :thumb_image
	include Placeholder
	def self.angular
		where(subtitle: 'Angular')
	end

	scope :ror, -> {where(subtitle: 'Ruby on rails')}

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
		self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
	end

	def self.by_postion
		order("position ASC")
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: %i[ show edit update destroy ]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :edit, :update, :create]}, site_admin: :all


  # GET /portfolios or /portfolios.json
  def index
    @portfolios = Portfolio.by_postion
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  # GET /portfolios/1 or /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
    3.times { @portfolio.technologies.build }
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios or /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: "Portfolio was successfully created." }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1 or /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: "Portfolio was successfully updated." }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1 or /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Portfolio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portfolio_params
      params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, technologies_attributes: [:name])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
        <% portfolio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= form.label :main_image %>
        <%= form.text_area :main_image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :thumb_image %>
        <%= form.text_area :thumb_image, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 15 %>
      </div>  
    </div>

    <hr />

    <div class="col-md-12">  
      <h2> Technologies used: </h2>

      <div class="form-group">
        <%= form.fields_for :technologies do |technology_form| %>
        <div class="form-group">
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name, class: 'form-control' %>
        </div>
        <% end %>
      </div>

    </div>
  </div>

  <div class="form-group">
    <%= form.submit 'Save Portfolio item', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>
    <div class="card-body">
      <p class="card-text">
        <span><%= portfolio.title %></span>
        <%= portfolio.subtitle %>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to 'Show', portfolio, class: "btn btn-sm btn-outline-secondary" %>
          <%= link_to 'Edit', edit_portfolio_path(portfolio), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<p id="notice"><%= notice %></p>

<h1>Angular Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Body</th>
      <th>Main image</th>
      <th>Thumb image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @angular_portfolio_items.each do |portfolio| %>
      <tr>
        <td><%= portfolio.title %></td>
        <td><%= portfolio.subtitle %></td>
        <td><%= portfolio.body %></td>
        <td><%= image_tag portfolio.main_image %></td>
        <td><%= image_tag portfolio.thumb_image %></td>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) if logged_in?(:site_admin)%></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
	<h1>Editing Portfolio</h1>

	<%= render 'form', portfolio: @portfolio %>

	<%= link_to 'Show', @portfolio %> |
	<%= link_to 'Back', portfolios_path %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row sortable">
      <%= render @portfolios %>
      <%= link_to 'New Portfolio', new_portfolio_path if logged_in?(:site_admin) %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
	<h1>New Portfolio</h1>

	<%= render 'form', portfolio: @portfolio %>

	<%= link_to 'Back', portfolios_path %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio.main_image %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio.title %></h1>

      <hr />
      <em><%= @portfolio.subtitle %></em>

      <p><%= @portfolio.body %></p>

      <hr />

      <h3>Technologies Used:</h3>

        <% @portfolio.technologies.each do |t| %>
        <%= t.name %>
        <% end %>
    </div>
  </div>
</div>